modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

Updates integrations for `UDR` and `WebUI` after moving auth keys to a separate DB

chore: Updating DB integrations after moving auth keys to a separate DB

---

modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/variables.tf
modules/sdcore-user-plane-k8s/README.md
modules/sdcore-user-plane-k8s/variables.tf

chore: bump to v1.4.0

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/main.tf
modules/sdcore-k8s/variables.tf
modules/sdcore-user-plane-k8s/variables.tf

Adds the channel variable to each charm, allowing us to version them independently

feat: Add variable for each charm

---

modules/sdcore-k8s/main.tf
modules/sdcore-k8s/variables.tf
modules/sdcore-user-plane-k8s/main.tf

Updates the name of the variable representing UPF channel

fix: Update UPF channel variable name in sdcore-user-plane-k8s

---

.github/workflows/terraform.yaml
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/variables.tf

- Updates NMS channel to 1.4/edge

chore: Updating NMS channel to 1.4/edge

---

modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/variables.tf
modules/sdcore-user-plane-k8s/variables.tf

Bump default channel risk to `beta`

chore: Bump default channel risk to beta

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/main.tf
modules/sdcore-k8s/variables.tf
modules/sdcore-user-plane-k8s/main.tf
modules/sdcore-user-plane-k8s/variables.tf

fix: Fixing sources for the modules

---

modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/variables.tf
modules/sdcore-user-plane-k8s/variables.tf

Fixes source branch for SD-Core COS configuration

fix: Fixing source branch for SD-Core COS configuration

---

.github/dependabot.yml
.github/workflows/terraform.yaml

- Schedules dependabot for release `1.4`
- Fixes config of `terraform.yaml`

chore: Scheduling dependabot for release 1.4

---

modules/external/alertmanager-k8s/terraform.tf
modules/external/catalogue-k8s/terraform.tf
modules/external/cos-configuration-k8s/terraform.tf
modules/external/cos-lite/terraform.tf
modules/external/grafana-agent-k8s/terraform.tf
modules/external/grafana-k8s/terraform.tf
modules/external/loki-k8s/terraform.tf
modules/external/mongodb-k8s/terraform.tf
modules/external/prometheus-k8s/terraform.tf
modules/external/traefik-k8s/terraform.tf
modules/sdcore-control-plane-k8s/terraform.tf
modules/sdcore-k8s/terraform.tf
modules/sdcore-user-plane-k8s/terraform.tf

chore: Update TF version to 0.12.0

---

modules/sdcore-control-plane-k8s/terraform.tf
modules/sdcore-k8s/terraform.tf
modules/sdcore-user-plane-k8s/terraform.tf

Root modules need to support TF modules in different versions.

chore: Support TF versions >= 0.11.0

---

modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/main.tf

Remove the database relation between the PCF and mongodb

feat: remove the database dependency on PCF

---

modules/sdcore-user-plane-k8s/variables.tf

fix:  Correct the typo by replacing AMF with UPF

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

Adds `sdcore-config` integration for AMF and AUSF

chore: Adds sdcore-config integration

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

Adds webui integration for nssf and udm

chore: Adds webui integration for nssf and udm

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

Add sdcore_config integrations for PCF and UDR

chore: Add sdcore_config integrations for PCF and UDR

---

modules/external/mongodb-k8s/README.md
modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/main.tf

This PR aims to remove the `database` relation from AMF charm.

feat: remove database integration for AMF

---

modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/main.tf
modules/sdcore-user-plane-k8s/README.md

This PR adds the new `metrics-endpoint` integration between SDCore charms and `grafana-agent`.

feat: add prometheus integration

---

README.md
modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/main.tf

- Remove the webui
- Replace webui by NMS on the sdcore_config endpoints
- Remove  sdcore_management integration
- Add db integrations to the NMS

feat: replace webui by NMS

---

modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/main.tf

This PR aims to remove the database relation for the SMF charm.

feat: remove database integration for SMF

---

modules/sdcore-k8s/main.tf

Fixes syntax in sdcore-k8s main.tf

fix: Fixes syntax in sdcore-k8s main.tf

---

modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-control-plane-k8s/outputs.tf
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/main.tf
modules/sdcore-k8s/outputs.tf
modules/sdcore-k8s/variables.tf
modules/sdcore-user-plane-k8s/README.md
modules/sdcore-user-plane-k8s/main.tf
modules/sdcore-user-plane-k8s/variables.tf

Refactor the Terraform module to follow spec CC006.
The integrations in particular have changed, and will require other modules to be changed at the same time. This is set to draft until all the PRs are ready.

chore: Refactor sdcore-k8s to follow spec CC006.

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

Adds webui_database integration for the NMS

fix: Adds webui_database integration for the NMS

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

Fixes `nms-fiveg-core-gnb` offer

fix: Fixes nms-fiveg-core-gnb offer

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/main.tf
modules/sdcore-k8s/variables.tf

Allows passing configuration to charms.

chore: Exposes configs for all charms

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

Fixes self-signed-certificated module config:
1. Sets correct base
2. Updates model variable name

fix: Fixes self-signed-certificated module config

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

fix: Fixes certificates endpoint

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

after changing to use self-signed-certificates in 1/stable, we need to update the base as well

fix: self signed certificates base

---

modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/main.tf
modules/sdcore-k8s/variables.tf

Fixes integration with self-signed-certificates:
- Updates the default channel
- Specifies a correct base
- Fixes endpoints

fix: Fixes integration with self-signed-certificates

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf
modules/sdcore-user-plane-k8s/main.tf

Fixes grafana-agent endpoints after switching to the official Grafana Agent TF module

fix: Fixes grafana-agent endpoints

---

modules/sdcore-control-plane-k8s/outputs.tf
modules/sdcore-k8s/outputs.tf
modules/sdcore-user-plane-k8s/outputs.tf

Fixes Grafana Agent endpoints in the outputs.tf

fix: Fixes Grafana Agent endpoints in the outputs.tf

---

modules/external/cos-lite/main.tf

fix: Fixes COS endpoints
