modules/sdcore-control-plane-k8s/outputs.tf
modules/sdcore-k8s/outputs.tf
modules/sdcore-user-plane-k8s/outputs.tf

Exposes Juju model name from SD-Core modules

chore: Exposing Juju model name from SD-Core modules

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf
modules/sdcore-user-plane-k8s/main.tf

Fixes setting the model name for cross-model relation. Old version would only work if COS was deployed at the same time as the SD-Core. Fixed version allows to deploy COS at any time.

fix: Fixing model name param in cross-model relations

---

modules/sdcore-control-plane-k8s/outputs.tf
modules/sdcore-k8s/outputs.tf
modules/sdcore-user-plane-k8s/outputs.tf

Reverts changes from https://github.com/canonical/terraform-juju-sdcore-k8s/pull/9

fix: Reverting exposure of the model name from sdcore modules

---

modules/sdcore-control-plane-k8s/README.md
modules/sdcore-k8s/README.md
modules/sdcore-user-plane-k8s/README.md

Updates READMEs for the SD-Core modules to pass the `-var-file` directly to `terraform apply`.
If the plan generated with `terraform plan` is not saved and passed to `terraform apply`, the `tfvars` file will be ignored and the deployment fails. Passing the `tfvars` file to `terraform apply` directly, eliminates a need of saving the plan.

fix: Update READMEs for the modules

---

modules/sdcore-user-plane-k8s/main.tf

Fixes logging endpoint on grafana-agent end of the `upf-logging` integration.

fix: Fixing grafana-agent endpoint for logging integration in sdcore-user-plane-k8s

---

modules/external/alertmanager-k8s/terraform.tf
modules/external/catalogue-k8s/terraform.tf
modules/external/cos-configuration-k8s/terraform.tf
modules/external/cos-lite/terraform.tf
modules/external/grafana-agent-k8s/terraform.tf
modules/external/grafana-k8s/terraform.tf
modules/external/loki-k8s/terraform.tf
modules/external/mongodb-k8s/terraform.tf
modules/external/prometheus-k8s/terraform.tf
modules/external/traefik-k8s/terraform.tf
modules/sdcore-control-plane-k8s/terraform.tf
modules/sdcore-k8s/terraform.tf
modules/sdcore-user-plane-k8s/terraform.tf

Bumps version of the Terraform provider to `0.11.0`

chore: Bumping version of the Terraform provider

---

.github/workflows/issues.yaml
.github/workflows/terraform.yaml

We use the release version of CI workflow instead of pointing to main. This prevents updates to the workflow causing the CI to fail here.

chore: use release version of github workflows

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/main.tf
modules/sdcore-k8s/variables.tf
modules/sdcore-user-plane-k8s/variables.tf

Uses a single channel variable for SD-Core charms

chore: Rolling back to a single channel variable for SD-Core charms

---

.github/workflows/terraform.yaml
modules/external/cos-lite/terraform.tf

Uses `github.ref` to checkout the right branch for the CI

fix: Uses github.ref to checkout the right branch for the CI

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

Adds `sdcore_config` integration for NRF and SMF
Should be merged after [SMF #226](https://github.com/canonical/sdcore-smf-k8s-operator/pull/226) and [NRF #238](https://github.com/canonical/sdcore-nrf-k8s-operator/pull/238)

chore: Adds sdcore_config integration for NRF and SMF

---

modules/external/mongodb-k8s/README.md
modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/main.tf

Reverts canonical/terraform-juju-sdcore-k8s#43 because this bug in upstream AMF has been observed: https://github.com/omec-project/amf/issues/261

revert: "feat: remove database integration for AMF"

---

modules/sdcore-control-plane-k8s/README.md
modules/sdcore-k8s/variables.tf
modules/sdcore-user-plane-k8s/README.md
modules/sdcore-user-plane/README.md
modules/sdcore-user-plane/main.tf
modules/sdcore-user-plane/outputs.tf
modules/sdcore-user-plane/terraform.tf
modules/sdcore-user-plane/variables.tf

This PR adds a root module for the Machine Charm based User Plane.
This PR depends on [changes in the UPF operator](https://github.com/canonical/sdcore-upf-operator/pull/112)

chore: Adds sdcore-user-plane (Machine Charm) module

---

modules/external/mongodb-k8s/README.md
modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/main.tf

This PR aims to remove the database relation from AMF charm.

feat: remove database integration for AMF

---

modules/external/alertmanager-k8s/terraform.tf
modules/external/catalogue-k8s/terraform.tf
modules/external/cos-configuration-k8s/terraform.tf
modules/external/grafana-agent-k8s/terraform.tf
modules/external/grafana-k8s/terraform.tf
modules/external/loki-k8s/terraform.tf
modules/external/mongodb-k8s/terraform.tf
modules/external/prometheus-k8s/terraform.tf
modules/external/traefik-k8s/terraform.tf

After `self-signed-certificates` bumped Juju Terraform provider version to 0.14.0 a conflict arised because Observability modules have been using 0.12.0. 
This PR allows Observability modules to use any version higher or equal than 0.12.0.

fix: Changes fixed version of the Terraform provider for Observability modules to a range (>= 0.12.0)

---

modules/external/alertmanager-k8s/terraform.tf
modules/external/catalogue-k8s/terraform.tf
modules/external/cos-configuration-k8s/terraform.tf
modules/external/grafana-agent-k8s/terraform.tf
modules/external/grafana-k8s/terraform.tf
modules/external/loki-k8s/terraform.tf
modules/external/mongodb-k8s/terraform.tf
modules/external/prometheus-k8s/terraform.tf
modules/external/traefik-k8s/terraform.tf

After self-signed-certificates bumped Juju Terraform provider version to 0.14.0 a conflict arised because Observability modules have been using 0.12.0.
This PR allows Observability modules to use any version higher or equal than 0.12.0.

fix: Update the TF modules version of Observability to range of >=0.12.0

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

This PR adds the TLS Certificates Integration to the NMS charm.
This integration is mandatory and the charm does not start the workload without it.
This integration is also added to traefik.
Once traefik implements `certificate transfer` interface we'll be able to use that instead of integrating Traefik with self-signed-certificates.  https://github.com/canonical/traefik-k8s-operator/issues/407

feat: add TLS integration to the NMS

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-k8s/main.tf

Traefik module does not follow spec CC006 so we need to use the endpoint on traefik integrations.
This PR fixes the error when deploying the module.

fix: traefik integration with certificates interface

---

CONTRIBUTING.md
modules/sdcore-control-plane-k8s/README.md
modules/sdcore-k8s/README.md
modules/sdcore-user-plane-k8s/README.md
modules/sdcore-user-plane/README.md

We decided to use Juju 3.5 and Microk8s 1.31-strict/stable  in SD-Core 1.5 channel. The reason why this PR updates the Juju and Microk8s versions in the documentation.

chore: use Juju 3.5 and Microk8s 1.31-strict/stable

---

modules/external/mongodb-k8s/README.md
modules/external/mongodb-k8s/variables.tf
modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/variables.tf

This PR sets the the `6/stable` channel for mongodb charm instead of `6/beta`

chore: move to channel 6/stable in mongodb

---

modules/sdcore-control-plane-k8s/README.md
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/README.md
modules/sdcore-k8s/variables.tf
modules/sdcore-user-plane-k8s/README.md
modules/sdcore-user-plane-k8s/variables.tf

Bumps charms channel to `1.6/edge` after creation of the `v1.5` release branch

chore: Bumps charms channel to 1.6/edge

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/main.tf
modules/sdcore-k8s/variables.tf

Removes `nssf_config` variable
This PR follows https://github.com/canonical/sdcore-nssf-k8s-operator/pull/369

chore: Removes nssf_config variable

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-control-plane-k8s/outputs.tf
modules/sdcore-k8s/main.tf
modules/sdcore-k8s/outputs.tf

Replaces `fiveg_gnb_identity` with `fiveg_core_gnb`
This PR is part of [TELCO-1450: Implement mechanism orchestrating network configuration between the Core and the RAN](https://warthogs.atlassian.net/browse/TELCO-1450)

feat: Replaces fiveg_gnb_identity with fiveg_core_gnb

---

.github/workflows/terraform.yaml

This change makes the CI trigger only on PR events, and not on push. This will prevent duplicate runs of CI jobs.

fix: remove duplicate ci jobs

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-control-plane-k8s/outputs.tf
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/main.tf
modules/sdcore-k8s/outputs.tf
modules/sdcore-k8s/variables.tf

This bumps the version of the NMS to get the `fiveg_core_gnb` integration to stay compatible with Charmed OAI RAN.

feat: Bump NMS for fiveg_core_gnb integration

---

modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/main.tf
modules/sdcore-k8s/variables.tf

Follows up on [NRF #462](https://github.com/canonical/sdcore-nrf-k8s-operator/pull/462)
Exposes `nrf_config` to allow setting `log-level`.

feat: Exposes NRF config

---

modules/sdcore-control-plane-k8s/variables.tf
modules/sdcore-k8s/variables.tf
modules/sdcore-user-plane-k8s/variables.tf

This PR changes the default channel for grafana-agent from `latest/stable` to `1/stable`. The former doesn't exist anymore.

fix: Sets grafana-agent channel to 1/stable

---

modules/external/cos-lite/variables.tf
modules/external/prometheus-k8s/variables.tf

COS-lite charms have been released to `1/stable` channel instead of `latest/stable`
- Alertmanager
- Catalogue
- COS configuration
- Grafana
- Loki
- Prometheus

fix: set COS lite charms channel to 1/stable

---

modules/external/alertmanager-k8s/variables.tf
modules/external/catalogue-k8s/variables.tf
modules/external/cos-configuration-k8s/variables.tf
modules/external/cos-lite/variables.tf
modules/external/grafana-agent-k8s/variables.tf
modules/external/grafana-k8s/variables.tf
modules/external/loki-k8s/variables.tf
modules/sdcore-control-plane-k8s/README.md
modules/sdcore-k8s/README.md
modules/sdcore-user-plane-k8s/README.md

COS-lite charms have been released to `1/stable` channel instead of latest/stable. This PR updates the default channel values for:
- Alertmanager
- Catalogue
- COS configuration
- Grafana
- Grafana agent
- Loki
- Prometheus
This PR is a continuation of https://github.com/canonical/terraform-juju-sdcore/pull/103

fix: set default channels to 1/stable for COS charms

---

modules/external/cos-lite/main.tf
modules/external/cos-lite/versions.tf
modules/sdcore-control-plane-k8s/main.tf
modules/sdcore-control-plane-k8s/versions.tf
modules/sdcore-k8s/main.tf
modules/sdcore-k8s/versions.tf
modules/sdcore-user-plane-k8s/main.tf
modules/sdcore-user-plane-k8s/versions.tf

This PR adjusts our TF modules to the latest `juju_offer` schema introduced in Juju TF provider `v0.20.0`

fix: Updates juju_offers to match the new schema
